---
- name: MariaDB
  hosts: all
  gather_facts: true
  become: true
  vars:
    mysql_root_password: "password"
  tasks:
    - name: install mariadb
      yum:
        name:
          - mariadb-server
          - mariadb
          - python3-PyMySQL

        state: latest
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
    - name: mysql_root_password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        check_implicit_admin: true
        password: "{{ mysql_root_password }}"
        host: localhost
    - name: remove remote root
      mysql_user:
        check_implicit_admin: true
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        host: "{{ ansible_fqdn }}"
        state: absent

    - name: Creating a New Database
      mysql_db:
       login_user: root
       login_password: "{{ mysql_root_password }}"
       name: compufy
       state: present

    - name: Creating yash user
      mysql_user:
       login_user: root
       login_password: "{{ mysql_root_password }}"
       name: yash
       password: 12345
       priv: '*.*:ALL'
       state: present
